joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
joint_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - servo1
    - servo2
    - servo3
    - servo4
    - servo5
  gains:
    servo1:
      p: 100
      i: 10
      d: 1
    servo2:
      p: 100
      i: 10
      d: 1
    servo3:
      p: 100
      i: 10
      d: 1
    servo4:
      p: 100
      i: 10
      d: 1
    servo5:
      p: 100
      i: 10
      d: 1
